services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/family-chart
      - /family-chart/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev